name: Dependabot Auto Merge
on:
  pull_request_target:
    types: [labeled, edited]

jobs:
  merge:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    name: Dependabot Auto Merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: bun i

      - name: Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          command: merge
          target: minor
          github-token: ${{ secrets.GH_TOKEN }}
